<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = if rerun.to_s.strip.empty?
  "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features"
else
  "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} #{rerun}"
end
std_opts = "-r features/ --format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>
default: --drb <%= std_opts %> features
wip: --drb --tags @wip:3 --wip features
rerun: --drb <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
